ALPHA = 2

MEMORY_DIMENSION = 10
VOCABULARY_DIMENSION = 20
SINGLE_WORD_EMBEDDING_DIMENSION = VOCABULARY_DIMENSION

N_NEIGHBOURS_IN_CONTEXT_EMBEDDING = 10
NEIGHBOUR_SHARE_OF_INFO_IN_EMBEDDING = 0.4 # Quantifies the fraction of the words embedding dedicated to the informations of the neighbouring words.
